name: Build Static ARMv7l Tools (musl)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3

      - name: Install musl-cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          wget https://musl.cc/arm-linux-musleabihf-cross.tgz
          tar -xzf arm-linux-musleabihf-cross.tgz -C /opt
          echo "/opt/arm-linux-musleabihf-cross/bin" >> $GITHUB_PATH

      - name: Build BusyBox
        run: |
          wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2
          tar -xf busybox-1.36.1.tar.bz2
          cd busybox-1.36.1
          make defconfig
          sed -i 's/^CONFIG_STATIC=.*/CONFIG_STATIC=y/' .config
          make -j$(nproc) CC="arm-linux-musleabihf-gcc" ARCH=arm CROSS_COMPILE=arm-linux-musleabihf-
          arm-linux-musleabihf-strip busybox

      - name: Build Dropbear
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2
          tar -xf dropbear-2022.83.tar.bz2
          cd dropbear-2022.83
          ./configure --host=arm-linux-musleabihf --enable-static --disable-zlib
          make -j$(nproc) PROGRAMS="dropbear dbclient dropbearkey"
          arm-linux-musleabihf-strip dropbear dbclient dropbearkey

      - name: Build GNU Netcat (Linux原生版本)
        run: |
          git clone https://github.com/dcantrell/nc.git
          cd nc
          ./autogen.sh
          ./configure --host=arm-linux-musleabihf --enable-static --disable-shared
          make -j$(nproc)
          arm-linux-musleabihf-strip src/nc

      - name: Package binaries
        run: |
          mkdir -p release/bin
          cp busybox-1.36.1/busybox release/bin/
          cp dropbear-2022.83/dropbear release/bin/
          cp dropbear-2022.83/dbclient release/bin/
          cp dropbear-2022.83/dropbearkey release/bin/
          cp nc/src/nc release/bin/
          tar -czvf armv7l-static-tools.tar.gz -C release .

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            armv7l-static-tools.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
