name: Build BusyBox & Dropbear

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential musl-tools git wget libncurses-dev

      - name: Set up cross compiler
        run: |
          wget https://musl.cc/arm-linux-musleabi-cross.tgz
          tar xzf arm-linux-musleabi-cross.tgz
          echo "$(pwd)/arm-linux-musleabi-cross/bin" >> $GITHUB_PATH

      - name: Build BusyBox
        run: |
          git clone https://github.com/mirror/busybox.git
          cd busybox
          git checkout remotes/origin/1_36_stable
          make defconfig
          sed -i 's/^CONFIG_STATIC[^=]*=.*/CONFIG_STATIC=y/' .config
          sed -i 's/^CONFIG_PIE[^=]*=.*/# CONFIG_PIE is not set/' .config
          echo -e "CONFIG_EXTRA_CFLAGS=-static\nCONFIG_EXTRA_LDFLAGS=-static\nCONFIG_EXTRA_LDLIBS=-static" >> .config
          echo "# CONFIG_BUILD_LIBBUSYBOX is not set" >> .config  # 禁用动态库
          yes '' | make oldconfig
          make LDFLAGS="--static" EXTRA_CFLAGS="-static" EXTRA_LDFLAGS="-static" EXTRA_LDLIBS="-static" ARCH=arm CROSS_COMPILE=arm-linux-musleabi- -j$(nproc)
          cp busybox ../busybox-armv7

      - name: Validate BusyBox
        run: |
          file busybox-armv7

      - name: Build Dropbear & Utilities
        run: |
          git clone https://github.com/mkj/dropbear
          cd dropbear
          ./configure --host=arm-linux-musleabi --disable-zlib --enable-static
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" -j$(nproc)
          mkdir -p ../dropbear-armv7
          cp dropbear dbclient dropbearkey dropbearconvert scp ../dropbear-armv7/

      - name: Validate Dropbear Tools
        run: |
          file dropbear-armv7/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: |
            busybox-armv7
            dropbear-armv7/*
