name: Build BusyBox & Dropbear

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential musl-tools git wget libncurses-dev

      - name: Set up cross compiler
        run: |
          wget https://musl.cc/arm-linux-musleabi-cross.tgz
          tar xzf arm-linux-musleabi-cross.tgz
          echo "$(pwd)/arm-linux-musleabi-cross/bin" >> $GITHUB_PATH

      - name: Build BusyBox
        run: |
          git clone https://git.busybox.net/busybox
          cd busybox
          make defconfig
          echo -e "CONFIG_STATIC=y\nCONFIG_EXTRA_CFLAGS=-static\nCONFIG_EXTRA_LDFLAGS=-static\nCONFIG_EXTRA_LDLIBS=-static" >> .config
          make oldconfig
          make ARCH=arm CROSS_COMPILE=arm-linux-musleabi- -j$(nproc)
          cp busybox ../busybox-armv7

      - name: Build Dropbear
        run: |
          git clone https://github.com/mkj/dropbear
          cd dropbear
          ./configure --host=arm-linux-musleabi --disable-zlib --enable-static
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" -j$(nproc)
          cp dropbear ../dropbear-armv7

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: |
            busybox-armv7
            dropbear-armv7
