name: Build for ARMv7 Musl

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get install -y \
          make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          libncurses-dev libssl-dev

    - name: Get BusyBox source
      run: git clone https://git.busybox.net/busybox busybox

    - name: Build BusyBox
      working-directory: busybox
      run: |
        sed -i 's/^# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

    - name: Get dropbear source
      run: git clone https://github.com/mkj/dropbear.git dropbear

    - name: Build dropbear
      working-directory: dropbear
      run: |
        ./configure --host=arm-linux-gnueabihf --disable-zlib --disable-pam --disable-shadow --disable-syslog
        make PROGRAMS="dropbear dbclient scp" MULTI=1 CROSS_COMPILE=arm-linux-gnueabihf-

    - name: Package binaries
      run: |
        tar czf armv7-musl-busybox-dropbear.tar.gz busybox/dropbear/dropbear busybox/dropbear/dbclient busybox/dropbear/scp busybox/busybox

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: armv7-musl-busybox-dropbear
        path: armv7-musl-busybox-dropbear.tar.gz
