name: Build Static ARMv7l Tools (musl)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3

      - name: Install musl-cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools automake libtool
          wget https://musl.cc/arm-linux-musleabihf-cross.tgz
          tar -xzf arm-linux-musleabihf-cross.tgz -C /opt
          echo "/opt/arm-linux-musleabihf-cross/bin" >> $GITHUB_PATH

      - name: Build Ncat (from Nmap)
        run: |
          # 安装 Ncat 依赖
          sudo apt-get install -y libpcap-dev libssl-dev
          # 下载 Nmap 源码（包含 Ncat）
          wget https://nmap.org/dist/nmap-7.94.tar.bz2
          tar -xf nmap-7.94.tar.bz2
          cd nmap-7.94
          # 配置静态编译
          ./configure \
            --host=arm-linux-musleabihf \
            --enable-static \
            --without-ndiff \
            --without-zenmap \
            --without-nmap-update \
            --with-pcap=linux \
            CC="arm-linux-musleabihf-gcc" \
            CXX="arm-linux-musleabihf-g++" \
            CFLAGS="-static -Os" \
            LDFLAGS="-static"
          # 编译 Ncat
          make -j$(nproc) ncat
          arm-linux-musleabihf-strip ncat/ncat

      - name: Build BusyBox
        run: |
          wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2
          tar -xf busybox-1.36.1.tar.bz2
          cd busybox-1.36.1
          make defconfig
          sed -i 's/^CONFIG_STATIC=.*/CONFIG_STATIC=y/' .config
          make -j$(nproc) CC="arm-linux-musleabihf-gcc" ARCH=arm CROSS_COMPILE=arm-linux-musleabihf-
          arm-linux-musleabihf-strip busybox

      - name: Build Dropbear
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2
          tar -xf dropbear-2022.83.tar.bz2
          cd dropbear-2022.83
          ./configure --host=arm-linux-musleabihf --enable-static --disable-zlib
          make -j$(nproc) PROGRAMS="dropbear dbclient dropbearkey"
          arm-linux-musleabihf-strip dropbear dbclient dropbearkey

      - name: Package binaries
        run: |
          mkdir -p release/bin
          cp nmap-7.94/ncat/ncat release/bin/
          cp busybox-1.36.1/busybox release/bin/
          cp dropbear-2022.83/dropbear release/bin/
          cp dropbear-2022.83/dbclient release/bin/
          cp dropbear-2022.83/dropbearkey release/bin/
          tar -czvf armv7l-static-tools.tar.gz -C release .

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            armv7l-static-tools.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
