name: Build Static ARMv7l Tools (safe)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  TARGET_ARCH: armv7l
  MUSL_CROSS: arm-linux-musleabi  
  SAFE_CFLAGS: "-march=armv5te -mno-unaligned-access -msoft-float -mfloat-abi=soft -mtune=generic-armv7-a -D__SOFTFP__ -nostdlib"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools file
          wget https://musl.cc/${MUSL_CROSS}-cross.tgz
          tar -xzf ${MUSL_CROSS}-cross.tgz -C /opt
          echo "/opt/${MUSL_CROSS}-cross/bin" >> $GITHUB_PATH

      - name: Build BusyBox (safe mode)
        run: |
          wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2
          tar -xf busybox-1.36.1.tar.bz2
          cd busybox-1.36.1
          make defconfig
          # 关键修复点
          sed -i "s/^CONFIG_STATIC=.*/CONFIG_STATIC=y/" .config
          sed -i "s/^CONFIG_EXTRA_CFLAGS=.*/CONFIG_EXTRA_CFLAGS=\"${SAFE_CFLAGS}\"/" .config
          sed -i "s/^CONFIG_EXTRA_LDLIBS=.*/CONFIG_EXTRA_LDLIBS=\"-lgcc_eh -lgcc\"/" .config
          # 显式指定所有编译参数
          make -j$(nproc) \
            CC="${MUSL_CROSS}-gcc" \
            CFLAGS="${SAFE_CFLAGS} -static" \
            LDFLAGS="${SAFE_CFLAGS} -static" \
            ARCH=arm \
            CROSS_COMPILE=${MUSL_CROSS}-
          ${MUSL_CROSS}-strip busybox

      - name: Package artifacts
        run: |
          mkdir -p release/bin
          cp busybox-1.36.1/busybox release/bin/
          tar -czvf ${TARGET_ARCH}-safe-tools.tar.gz -C release .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${TARGET_ARCH}-artifacts
          path: |
            release
